### PR TITLE
[9.12.r1] input: sec_ts: Convert debug information to input_dbg

### PR DESCRIPTION
**Pull request by Thaodan**
Convert all debug information that falsely used input_dbg. The driver doesn't really differentiate between debug or diagnostic information that is helpful for the user such as firmware version or supported features. In quite many cases the  are mixed in between debug information with messages such as start foo and end foo.

I changed all debug information to input_dbg except those regarding firmware, config versions and supported features.

Messages such as screen of and on should be gone unless ts->debug_flags is true.

### CODE REVIEW

**Comment by Thaodan** [comment]
cc: @jerpelea @mlehtima

**Comment by voidanix** [comment]
@Thaodan, commit 27e7bb91f9357a47fd21dfb6b21093aa1ba51982 (946285ebea53406d0234aac4081a8a9a8162cbcb in this PR) fails to build:

```
/bruh/aosp/kernel/sony/msm-4.19/kernel/drivers/input/touchscreen/sec_ts/sec_ts.c:1280:13: error: use of undeclared identifier 'ts'
                input_dbg(ts->debug_flag, dev, "%s: irq_type property:%X, %d\n", __func__,
                          ^
/bruh/aosp/kernel/sony/msm-4.19/kernel/drivers/input/touchscreen/sec_ts/sec_ts.c:1368:12: error: use of undeclared identifier 'ts'
        input_dbg(ts->debug_flag, &client->dev, "%s: i2c buffer limit: %d, lcd_id:%06X, bringup:%d, FW:%s(%d), id:%d,%d, mis_cal:%d dex:%d, gesture:%d\n",
                  ^
/bruh/aosp/kernel/sony/msm-4.19/kernel/drivers/input/touchscreen/sec_ts/sec_ts.c:1403:14: error: use of undeclared identifier 'ts'
                        input_dbg(ts->debug_flag, &client->dev, "watchdog_delay_ms: %d\n",
                                  ^
3 errors generated.
```

This happens with clang r416183b (A12), any chance you could take a look?

**Comment by MarijnS95** [comment]
@voidanix oh yeah, that's bad. I don't know what I find worse about this project, the fact that I have to bisect some **unrelated** boot-breaking kernel issue every time I dare to start looking into contributing new features/fixes elsewhere (and _never_ get to actually doing that...), or the fact that it is _not even bisectable in the first place_.

In fact...

```
27e7bb91f9357a47fd21dfb6b21093aa1ba51982 is the first bad commit
commit 27e7bb91f9357a47fd21dfb6b21093aa1ba51982
Author: Björn Bidar <bjorn.bidar@jolla.com>
Date:   Thu Jan 12 08:13:07 2023 +0200

    input: sec_ts: Convert debug information to input_dbg

    Convert all debug information that falsely used input_dbg.
    The driver doesn't really differentiate between debug or diagnostic information that
    is helpful for the user such as firmware version or supported
    features. In quite many cases the  are mixed in between debug
    information with messages such as start foo and end foo.

    I changed all debug information to input_dbg except those regarding
    firmware, config versions and supported features.

    Messages such as screen of and on should be gone unless
    ts->debug_flags is true.

    Signed-off-by: Björn Bidar <bjorn.bidar@jolla.com>

 drivers/input/touchscreen/sec_ts/sec_ts.c          | 160 +++++-----
 drivers/input/touchscreen/sec_ts/sec_ts_fn.c       | 350 ++++++++++-----------
 .../input/touchscreen/sec_ts/sec_ts_only_vendor.c  |  12 +-
 drivers/input/touchscreen/sec_ts_lena/sec_ts.c     | 110 +++----
 drivers/input/touchscreen/sec_ts_lena/sec_ts_fn.c  | 168 +++++-----
 5 files changed, 400 insertions(+), 400 deletions(-)
```

PR incoming, but let this please be the last.
