### PR TITLE
[7.1.r1] Revert "lib/genalloc.c: use vzalloc_node() to allocate the bitmap"

### LINKED ISSUE #530: [Yoshino][Lilac] Kernel 4.14 bootloops.
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.167
**Android version:** android-10.0.0_r21
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v3_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Used Kernel-Compiler:** Clang

**Description**
With the most recent version my phone hangs in boot-loop. It is not possible to connect adb.
Tried two different kernels with the same result:

- Most recent kernel: https://github.com/sonyxperiadev/kernel/commit/b66e549327f0f06f2e248fec288902ed18904571
- Most recent kernel: https://github.com/sonyxperiadev/kernel/commit/b66e549327f0f06f2e248fec288902ed18904571 + reverted: https://github.com/sonyxperiadev/kernel/commit/b0ee9746150cd1590c58bf55a861f000c0f31482

Flashed a k4.9 recovery.img but the phone did not boot into recovery after crashing, but a double crash occurred. So I am unable to recover `/sys/fs/pstore` contents.

To build it, I have used following script:
https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh

I have flashed following images from the 4.14 build:
```
stefan@mars:~/android/bin/current-4.14$ ls -l
insgesamt 28
lrwxrwxrwx 1 stefan stefan 33 Feb  1 16:46 boot.img -> ../2020.02.01-4.14/boot-clang.img
lrwxrwxrwx 1 stefan stefan 28 Feb  1 18:39 cache.img -> ../2020.02.01-4.14/cache.img
lrwxrwxrwx 1 stefan stefan 60 Feb  1 16:47 oem.img -> ../SW_binaries_for_Xperia_Android_10.0.7.1_r1_v3_yoshino.img
lrwxrwxrwx 1 stefan stefan 31 Feb  1 16:46 recovery.img -> ../2020.02.01-4.14/recovery.img
lrwxrwxrwx 1 stefan stefan 29 Feb  1 16:46 system.img -> ../2020.02.01-4.14/system.img
lrwxrwxrwx 1 stefan stefan 31 Feb  1 16:46 userdata.img -> ../2020.02.01-4.14/userdata.img
lrwxrwxrwx 1 stefan stefan 29 Feb  1 16:46 vendor.img -> ../2020.02.01-4.14/vendor.img
```

### PR DESCRIPTION
**Pull request by stefanhh0**
Fixes sonyxperiadev/bug_tracker#530

This reverts commit d84f622a917d3737dcaedf9c981e660e6bfdb19b.

This causes Yoshino to fail to boot, as discovered with a git bisect.
I do not see any real reason why this should happen but at the same
time, Qualcomm devices are probably not subject to the issue that the
commit notes.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

### CODE REVIEW

**Comment by stefanhh0** [comment]
Tested just the kernel-build, no compilation errors due to that revert.

I haven't tested it yet on my phone, but to me it seems to be a hot candidate which lets yoshino/lilac fail.

I don't know if it can be integrated without further testing. I just don't have the time this week. Earliest on weekend...

**Comment by stblr** [comment]
Tested and confirmed to work on Lilac.
